### PR TITLE
Offline support + elephant VR

### PR DESCRIPTION
**Pull request by AVGP**

### CODE REVIEW

**Comment by AVGP** [comment]
Sorry, wrong fork 😱

**Comment by urish** [comment]
Elephant? I wonder!

**Comment by AVGP** [comment]
Yeah, @m-ke has replaced the T-Rex with an Elephant & it's kinda hilarious!

2017-12-13 17:35 GMT+01:00 Uri Shaked <notifications@github.com>:

**Comment by m-ke** [comment]
It's really funny. https://github.com/m-ke/elephant-vr

**Pull request closed without merging**
